### PR TITLE
create videos of raw gaze with fixations

### PR DESCRIPTION
**Pull request by dev-jam**
I added the creation of gaze videos. It plots the raw gaze in red and blue, and plots the fixation in green. The fixation dot size increases with time dependent on the fixation duration.

### CODE REVIEW

**Comment by marcus-nystrom** [comment]
Great! However, I'd prefer to have this as a separate script called, for instance, plot_scanpath_video.py.
Could you modify your pull request? 
Thanks, 
Marcus

**Comment by dev-jam** [comment]
It is a separate script now. O, I just see I missed your filename suggestion. I named it plot_gaze_video.py.
It also creates videos of the raw gaze only if there are no detected fixations.

**Comment by marcus-nystrom** [comment]
> It is a separate script now. O, I just see I missed your filename suggestion. I named it plot_gaze_video.py. It also creates videos of the raw gaze if there are no detected fixations.
> 
> I also noticed that the output of detect_fixations in allfixations.txt is always a bit different after a run (not deterministic). Does the I2MC algorithm use some randomness in its algorithm or is this a bug? Gonna take a look into the code tomorrow and otherwise check with Roy.

The I2MC uses k-means clustering, so there's indeed a random component there. Should however be little variability in output between different runs.

**Comment by dev-jam** [comment]
> The I2MC uses k-means clustering, so there's indeed a random component there. Should however be little variability in output between different runs.

Thanks, that explains the small variability.

I see you changed the codec from 'avc1' to 'mp4v', be aware that the videos are around 20x bigger in size with this codec. 
'avc1' seems surprisingly efficient with static backgrounds. I also did not implement downsampling from 300/600 fps to a more common 30/60 fps, because it did not seem necessary with this codec. What was your motivation for the 'mp4v' codec?

**Pull request merged**
